### ISSUE TITLE
inline replies get hidden

### ISSUE THREAD

**Issue by unhammer** [org-mime/org-mime#10]
This might be related to https://github.com/org-mime/org-mime/issues/8 but I'm  not sure I understood the resolution. If I hit `F` in gnus, I get a buffer with initial `>`'s in front of each quoted line. Now, if I add some stuff in between, e.g.

```
D T <dt@apocalyptics.org> writes:

> Grave men, near death, who see with blinding sight

Thank you for your report, I agree this is serious.

> Blind eyes could blaze like meteors and be gay,

Could you please provide a bit more detail?

> Rage, rage against the dying of the light.

That's actually a *feature*, not a bug.

If you need any information don't hesitate to get in contact with me.
```

It looks like this in e.g. Fastmail:

![re_rage](https://user-images.githubusercontent.com/56868/31278101-0908b344-aaa4-11e7-98e1-f921f493621f.png)

Is there no way to do inline-quoting with org-mime-htmlize?

**Comment by unhammer** [comment]
Oh, I just needed to `(setq org-mime-beautify-quoted-mail nil)` :-)

Since emacs users are likely to know how to do inline-replies, perhaps the default should be nil? 

In any case, I think it would be a good idea to have a section in the README saying that if you beautify quoted mail, inline replies will get hidden.

(Ideally, `org-mime-htmlize` would warn in those cases, but I realise that could get complicated.)

**Comment by redguardtoo** [comment]
e7fdb53 README (Chen Bin)

**Comment by unhammer** [comment]
https://github.com/org-mime/org-mime/commit/e3329c7c4df120b08b7cbdc6925a67c84b510e74#diff-aacb4ce123f9200898dff4a35e6a8461L87 doesn't warn that inline replies will get hidden though, I think that's important enough that it should be mentioned

**Comment by redguardtoo** [comment]
fixed the issue. a6e1048 beautify quoted mail properly (Chen Bin)

**Comment by jkitchin** [comment]
Maybe this should be closed?
