### ISSUE TITLE
Beautifying quoted mail fails in new messages

### ISSUE THREAD

**Issue by malcolmpurvis** [org-mime/org-mime#11]
Using the latest version of org-mime (20171008.644) if I create a new message in Gnus whose body is 'Hello World' and then run the command org-mime-htmlize, it fails with the error:

Search failed: "^[^ ]*&gt; "

If I disable quoted mail (setq org-mime-beautify-quoted-mail nil) the command works.

**Comment by redguardtoo** [comment]
f1175e3 can htmlize new mail (Chen Bin)
