### ISSUE TITLE
keep gpg signatures outside of multipart?

### ISSUE THREAD

**Issue by unhammer** [org-mime/org-mime#12]
```
<#secure method=pgpmime mode=sign>
Please send your answer to Old Pink, care of the funny farm, Chalfont.

```
after org-mime-htmlize becomes

```
<#multipart type=alternative><#part type=text/plain>#+OPTIONS: latex:t toc:nil H:3
<#secure method=pgpmime mode=sign>
Please send your answer to Old Pink, care of the funny farm, Chalfont.
<#multipart type=related><#part type=text/html><p>
&lt;#secure method=pgpmime mode=sign&gt;<br />
Please send your answer to Old Pink, care of the funny farm, Chalfont.<br />
</p>
<#/multipart>
<#/multipart>
```

should probably be

```
<#secure method=pgpmime mode=sign>
<#multipart type=alternative><#part type=text/plain>
Please send your answer to Old Pink, care of the funny farm, Chalfont.
<#multipart type=related><#part type=text/html><p>
Please send your answer to Old Pink, care of the funny farm, Chalfont.<br />
</p>
<#/multipart>
<#/multipart>
```

**Comment by unhammer** [comment]
This is standard message-mode formatting though, and people do have things like `(add-hook 'message-setup-hook #'mml-secure-message-sign)` [in their inits](https://duckduckgo.com/?q=(add-hook+%27message-setup-hook+%23%27mml-secure-message-sign)&t=canonical&ia=web). Would it be possible for org-mime-htmlize to skip such lines? (I'm guessing there are other similar things too with the format `<#keyword attr=val>`)

**Comment by redguardtoo** [comment]
I add a new callback `org-mime-find-html-start` to give you another chance to tweak html start.

In you case, you can use it this way:
```lisp
(setq org-mime-find-html-start
      (lambda (start)
        (save-excursion
          (goto-char start)
          (search-forward "<#secure method=pgpmime mode=sign>")
          (+ (point) 1))))
```

**Comment by unhammer** [comment]
should it be defcustom instead of defvar maybe?

**Comment by redguardtoo** [comment]
Yes, Pull request is welcome.

**Comment by unhammer** [comment]
https://github.com/org-mime/org-mime/pull/15/files

**Comment by jkitchin** [comment]
Maybe this should be closed?

**Comment by unhammer** [comment]
probably :) I'll just go ahead …

**Comment by redguardtoo** [comment]
23cc52b donot htmlize security signature and attachment (Chen Bin)
