### ISSUE TITLE
"#+OPTIONS: latex:t toc:nil H:3" in plain-text part

### ISSUE THREAD

**Issue by unhammer** [org-mime/org-mime#13]
```
That’s 10 ‘programmer minutes’, i.e. less than a day.
```
after org-mime-htmlize becomes
```
<#multipart type=alternative><#part type=text/plain>#+OPTIONS: latex:t toc:nil H:3
That’s 10 ‘programmer minutes’, i.e. less than a day.
<#multipart type=related><#part type=text/html><p>
That’s 10 ‘programmer minutes’, i.e. less than a day.<br />
</p>
<#/multipart>
<#/multipart>
```

– could we remove the `#+OPTIONS: latex:t toc:nil H:3`  from the plain-text part?

**Comment by redguardtoo** [comment]
We need remember the export options of original mail.

But you can always tweak the finalized html boy in `org-mime-html-hook`, see https://emacs.stackexchange.com/questions/13819/how-to-use-css-to-change-styling-of-elements-in-org-mime-emails

Inside that hook, the current buffer is the finalized html, you can change the content of that buffer.

```lisp
(add-hook 'org-mime-html-hook
      (lambda ()
        (while (re-search-forward "#+OPTIONS: latex:t toc:nil H:3" nil t)
         (replace-match "#+OPTIONS: latex:t toc:nil H:3" ))))
```

**Comment by unhammer** [comment]
`org-mime-html-hook` only touches html, not plain text; #14 works for me though (and feels less hacky, though I haven't read through all the source yet)

**Comment by redguardtoo** [comment]
sorry, I misunderstood your issue.
Thanks for the pull request.
