### ISSUE TITLE
(setq org-html-with-latex nil) sometimes useful

### ISSUE THREAD

**Issue by ouboub** [org-mime/org-mime#16]
Hi
I just realized that 
the code contains the line hard coded line
(org-html-with-latex 'dvipng)
the problem is that sometimes I want to send messages like this
* Matlab code
 f=@(t,y)[-t*y^2];
 [t,y]=ode45(f,[0 1],1);
 t=[t(1),t(end)];
 y=[y(1),y(end)];
 disp('\begin{align*}')
 fprintf('t = [%g  \\quad %g]  \\\\\n', t)
 fprintf('y = [%g  \\qquad %g] \n', y)
 disp('\end{align*}')

which I want to transform to html but ignore the latex syntax since it cannot be compiled.

but with the current code this is impossible

regards

Uwe Brauer

**Comment by redguardtoo** [comment]
`(setq org-mime-org-html-with-latex-default nil)`
See 64a3f56 (setq org-html-with-latex nil) sometimes useful #16 (Chen Bin)

**Comment by ouboub** [comment]
Thanks, when will this be in upstream? that is in in elpa/melpa?

**Comment by redguardtoo** [comment]
should be already in melpa now.

**Comment by jkitchin** [comment]
Maybe this should be closed?
