### ISSUE TITLE
org-mime-org-[buffer|subtree]-htmlize fails if klipsify non-nil

### ISSUE THREAD

**Issue by titaniumbones** [org-mime/org-mime#26]
setting klipsify to non-nil causes org-mime to error out inside of `org-mime-replace-images`. I've fixed it two ways:

- add `(org-html-klipsify-src nil)` to the `(let* ` in `org-mime-org-buffer-htmlize` 
- add a couple of lines to `org-mime-replace-images` to leave remote references alone (by filtering out src values that start with http[s](. I can provide a patch if you like but as I'm struggling with a number of issues right now I don't have a clean fix for any of them!

**Comment by redguardtoo** [comment]
sure. first way looks simpler, could you send me the patch?

**Comment by titaniumbones** [comment]
I did a one-line PR in #28 !
