### ISSUE TITLE
2 issues w/ org-mime-htmlize-subtree

### ISSUE THREAD

**Issue by titaniumbones** [org-mime/org-mime#3]
(1) iI think you want `org-back-to-heading` instead of `org-up-heading-safe` (getting the parent subtree instead of the intended one)
(2) MAIL_CC and MAIL_BCC show up in the message body instead of as arguments; I wonder if the behaviour of someo f hte other functions has chancged since subtree was accidentally removed:

Here's the  text of a message generaged by `org-mime-htmlize-subtree:
```
Cc: moptop99@gmail.com
To: matt.price@utoronto.ca
Subject: send an email w org-mime-subtree
From: Matt Price <matt.price@utoronto.ca>
--text follows this line--
<#multipart type=alternative><#part type=text/plain>:MAIL_TO: matt.price@utoronto.ca :MAIL_CC: moptop99@gmail.com
All of this *should* go into my emacs-init but it breaks stuff...


test inner
==========

  testing
<#part type=text/html><p>
:MAIL_TO:  matt.price@utoronto.ca
:MAIL_CC:  moptop99@gmail.com
</p>
<p>
All of this <b>should</b> go into my emacs-init but it breaks stuff&#x2026;
</p>
<div id="outline-container-org5b3cb3c" class="outline-2">
<h2 id="org5b3cb3c">test inner</h2>
<div class="outline-text-2" id="text-org5b3cb3c">
<p>
testing</p>
</div>
</div>
<#/multipart>
```

**Comment by redguardtoo** [comment]
I understand `org-back-to-heading` just goes one level up. That's not my code, I think it's from 3rd patch. I could add some option to let user select the the style.

Could you re-test with the latest version of org-mime? and give your Emacs version and org version. I can't reproduce the issue.

**Comment by redguardtoo** [comment]
Try version 0.0.5 I released right now.

**Comment by weshmashian** [comment]
I've managed to resolve the first issue by convincing `org-mime-org-subtree-htmlize` to behave like before (see code below). Function should either use `org-back-to-heading` or revert to `org-narrow-to-subtree` behavior. The way it is now it is trying to export entire parent which is not obvious or expected.

I'm having the same issue with extra properties showing up in mail body. Comparing it to last known good version (from org-mode), subtree function explicitly skipped the property drawer. In the end, I think I'll try to do the same, as I'm not liking the recent changes too much.

```el
(defun mc/fix-org-mime-subtree (func)
  (save-restriction
    (org-narrow-to-subtree)
    (funcall func)))

(advice-add 'org-mime-org-subtree-htmlize :around #'mc/fix-org-mime-subtree)
```

**Comment by redguardtoo** [comment]
I will let user to customize the way to go up in subtree.

For the drawer, could you give me more details?

**Comment by redguardtoo** [comment]
In v0.0.6, you can `(setq org-mime-up-subtree-heading 'org-up-heading-safe)`.

As I tested, 24.3, 24.4, 25.1 works with current version. Patches are welcome if you find any issue.

**Comment by titaniumbones** [comment]
Hoping to test this out in the next day or two. I haven't had the
opportunity for the last week -- sorry for the delay and htanks for your
work!

matt

Chen Bin <notifications@github.com> writes:

> In v0.0.6, you can (setq org-mime-up-subtree-heading 'org-up-heading-safe).
>
> As I tested, 24.3, 24.4, 25.1 works with current version. Patches are welcome if you find any issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by weshmashian** [comment]
Sorry, forgot about this issue...

> For the drawer, could you give me more details?

Given the following org example:
```
* This is just a test
  :PROPERTIES:
  :MAIL_TO: jsmith@example.com
  :MAIL_FMT: ascii
  :foo: bar
  :END:

Text goes here...
```

Expectation is that the resulting buffer would look something like:
```
To: jsmith@example.com
Subject: This is just a test
From: me@example.com
--text follows this line--
Text goes here...
```

However, it ends up looking like:
```
To: jsmith@example.com
Subject: This is just a test
From: me@example.com
--text follows this line--
:MAIL_TO: jsmith@example.com :MAIL_FMT: ascii :foo: bar
Text goes here...
```

"Original" org-mime used to strip the drawer after it used up properties it was interested in.

**Comment by redguardtoo** [comment]
Can only reproduce at emacs 24.3

**Comment by weshmashian** [comment]
For what it's worth, I've extracted the original org-mime.el from Org's repo, renamed it to avoid any namespace clashes, and made it available in [it's own repository](https://gitlab.com/weshmashian/org-pantomime). This fixed my issues, so I guess this can be closed.

**Comment by redguardtoo** [comment]
dd1b988 remove drawers when org-mime-htmlize-subtree at emacs 24.3 (Chen Bin)
