### ISSUE TITLE
Wrong type argument: char-or-string-p, nil

### ISSUE THREAD

**Issue by asikstel** [org-mime/org-mime#33]
Using org-mime from Melpa, org 9.1.9, emacs 26.1 from brew cask on Mac OS I get the following error when I try to send a trivial org note
```
* H1
#+OPTIONS: tex:imagemagick
#+OPTIONS: toc:0
** H2
$s=x^2$
```
by email:
org-mime-compose: Wrong type argument: char-or-string-p, nil

**Comment by redguardtoo** [comment]
`#+OPTIONS: tex:imagemagick` what does this mean? How should I setup text (I installed texlive on debian)?

I got below error message when `M-x org-mime-org-buffer-htmlize`

```
Creating LaTeX Image...
org-compile-file: File "/tmp/orgtexPPgyfO.pdf" wasn’t produced.  Please adjust ‘imagemagick’ part of ‘org-preview-latex-process-alist’.
```

**Comment by asikstel** [comment]
I suppose this option forces org to use imagemagick while converting latex to html (instead of mathjax, etc). I don't have a linux machine right now, so cannot test.
Anyways, without any options I get the same error.

**Comment by redguardtoo** [comment]
I can't reproduce the issue 
`M-x toggle-debug-on-error`, reproduce the issue and send me the error message.

**Comment by asikstel** [comment]
Most recent version is installed and this is the debugger output:

```

Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  org-mime-insert-html-content("#+BEGIN_EXPORT<GENERATED HTML DELETED FOR BREVITY>+END_EXPORT" "<PATH-TO-ORG>/test.org" "#+BEGIN_EXPORT <GENERATED HTML DELETED FOR BREVITY> END_EXPORT" nil)
  org-mime-compose("#+BEGIN_EXPORT +END_EXPORT" "<PATH-TO-ORG>/test.org" nil "test" nil nil)
  org-mime-org-buffer-htmlize()
  funcall-interactively(org-mime-org-buffer-htmlize)
  call-interactively(org-mime-org-buffer-htmlize nil nil)
  command-execute(org-mime-org-buffer-htmlize)
```

**Comment by redguardtoo** [comment]
I still can't see why it failed.

`M-x eval-expression (org-mime-insert-html-content "#+BEGIN_EXPORT<GENERATED HTML DELETED FOR BREVITY>+END_EXPORT" "<PATH-TO-ORG>/test.org" "#+BEGIN_EXPORT <GENERATED HTML DELETED FOR BREVITY> END_EXPORT" nil)` work fine at my computer.

I need double check you are using the latest version.

Open latest `org-mime.el`, `M-x eval-buffer`, then swtich buffer to your org file. Try to reproduce the issue. Send me the error output

**Comment by asikstel** [comment]
Ok, so I did exactly what you proposed. The debugger output is now different:

```
  insert(nil)
  (let* ((files (org-mime-extract-non-image-files)) (org-html-with-latex org-mime-org-html-with-latex-default) (org-html-link-org-files-as-html nil) (org-link-file-path-type 'absolute) (org-export-preserve-breaks org-mime-preserve-breaks) (org-html-htmlize-output-type 'inline-css) (org-export-htmlize-output-type 'inline-css) (html-and-images (org-mime-replace-images (org-mime--export-string s 'html opts) file)) (images (cdr html-and-images)) (html (org-mime-apply-html-hook (car html-and-images)))) (if files (progn (mapc (function (lambda (f) (setq html (replace-regexp-in-string (format "<a href=\"%s\">%s</a>" (regexp-quote f) (regexp-quote f)) (format "%s (attached)" (file-name-nondirectory f)) html)))) files))) (insert (org-mime-multipart html (mapconcat 'identity images "\n"))) (if files (progn (mapc (function (lambda (f) (if org-mime-debug (progn (message "attaching: %s" f))) (mml-attach-file f))) files))))
  org-mime-insert-html-content("#+BEGIN_EXPORT ... +END_EXPORT"
  "<PATH>/test.org" "#+BEGIN_EXPORT ... #+END_EXPORT" nil)
  (let* ((export-opts (org-mime-get-export-options subtreep)) str) (if (featurep 'message) nil (require 'message)) (message-mail to subject headers nil) (message-goto-body) (setq str (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert body) (goto-char (point-min)) (run-hooks 'org-mime-pre-html-hook) (buffer-string)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) (org-mime-insert-html-content body file str export-opts))
  org-mime-compose("#+BEGIN_EXPORT ... +END_EXPORT" "/Users/aleks/Documents/Notes/yo.org" nil "yo" nil nil)
  (let* ((org-html-klipsify-src nil) (region-p (org-region-active-p)) (file (buffer-file-name (current-buffer))) (keywords (org-mime-extract-keywords)) (subject (or (cdr (assoc "MAIL_SUBJECT" keywords)) (org-mime--get-buffer-title) (if (not file) (buffer-name (buffer-base-buffer)) (file-name-sans-extension (file-name-nondirectory file))))) (html-body (org-mime-get-exported-content nil)) (to (cdr (assoc "MAIL_TO" keywords))) (cc (cdr (assoc "MAIL_CC" keywords))) (bcc (cdr (assoc "MAIL_BCC" keywords))) (other-headers (org-mime-build-mail-other-headers cc bcc))) (org-mime-compose html-body file to subject other-headers nil) (message-goto-to))
  org-mime-org-buffer-htmlize()
  funcall-interactively(org-mime-org-buffer-htmlize)
  call-interactively(org-mime-org-buffer-htmlize record nil)
  command-execute(org-mime-org-buffer-htmlize record)
  execute-extended-command(nil "org-mime-org-buffer-htmlize" "org-mime-org-buf")
  funcall-interactively(execute-extended-command nil "org-mime-org-buffer-htmlize" "org-mime-org-buf")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by redguardtoo** [comment]
Thanks. 

8de4bb6 image could be nil (Chen Bin)

**Comment by asikstel** [comment]
I've set it up via latexmk as following:

```
(setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
```

when I run C-c C-e and then publish as html, org works flawlessly.

Thanks for the update!
So I've installed it, org-mime-org-buffer-htmlize runs without complaining. Unfortunately,Ω the generated email is empty except for the filename in the subject. However, I've tested it with mu4e. It is not supported yet?

**Comment by redguardtoo** [comment]
I need some time to investigate. I don't think `mu4e` is related.

**Comment by asikstel** [comment]
Ok, no problem. Thanks a lot for the great support so far:)

**Comment by redguardtoo** [comment]
I did some investigation.

For org file:
```
* H1
#+OPTIONS: tex:imagemagick
#+OPTIONS: toc:0
** H2
$s=x^2$
```

This has nothing to do with `org-mime`, it's purely org export setup.

`imagemagick` is the keyword to lookup command line process in `org-preview-latex-process-alist`

Here are the two commands I found.
`pdflatex -interaction nonstopmode -output-directory %o %f` and `convert -density %D -trim -antialias %f -quality 100 %O`

You can run `ls ls /tmp/orgtex*` to get log/pdf/png files generated by org-export process

To generate pdf file, I need install `texlive-full` on debian. To convert the pdf to png file, I need modify imagemagick's default security policy. See https://stackoverflow.com/questions/42928765/convertnot-authorized-aaaa-error-constitute-c-readimage-453

**Comment by redguardtoo** [comment]
Can you send me a more complex org file containing tex? I want to setup some unit test for tex conversion.

**Comment by asikstel** [comment]
Sorry for the late reply!

```
#+LaTeX_+HEADER: \usepackage{amsmath} 
* Header1  Added: [2019-05-16 Thu 10:36]                          :tag1:tag2:
  - some text  $n\cdot(A_x, A_y, A_z)$
    - subpt1
    - subpt2
  - more text
  - more text ~std::runtime_exception("..." + str(norm))~
  - more text
  - even more text
** TODO "large" equation:
\begin{align}
& \vec{u}_t + \vec{f}_x\left(\vec{u}\right)  = 0 \\
& p(\rho) = \alpha\rho^\gamma
\end{align}
*** Header 3
some text and an equation $f = \frac{\sin(x)}{x}$ and also some code

#+BEGIN_SRC

f = auto [](){}();
void f(){
  do_sth(1,b,c);
}
#+END_SRC
```

So I think this example contains everything I'd use in org. IF you need something more, let me know.
