### ISSUE TITLE
LaTeX fragment not exported correctly

### ISSUE THREAD

**Issue by yangsheng6810** [org-mime/org-mime#34]
Recently `org-mime-htmlize` stops compiling LaTeX fragments, e.g. `$\frac{1}{2}$`, to pictures. It seems org-mime is using the default option for html export which uses MathJax instead of the dvipng backend suited for emails. I am able to workaround with the following.
```emacs-lisp
(setq org-mime-export-options '(:with-latex dvipng))
```

org-mime version: 20190513.1337
org-plus-contrib version: 20190624

**Comment by redguardtoo** [comment]
`M-x toggle-debug-on-error`, send me the full message.

**Comment by yangsheng6810** [comment]
No error is reported. `org-mime-htmlize` just happily transforms equations to MathJax form, i.e. `$\sqrt{2}$` to `\(\sqrt(2)\)`.

**Comment by redguardtoo** [comment]
Is it related to https://github.com/org-mime/org-mime/issues/33#issuecomment-479367124

**Comment by yangsheng6810** [comment]
I don't think so. I am not specifying any options to the org file, and it can happen when only contains
```latex
$\frac{1}{2}$
```
Here are some investigations I made. The default value of `org-html-with-latex` in ox-html.el is `t`, which means using MathJax.js. In `org-html-latex-fragment`, it handles latex fragment with `processing-type` which comes from `(plist-get info :with-latex)` on argument `info`. If `processing-type` is `dvipng`, then math is correctly transformed into pictures. This `info` can be traced all the way back to `opts` in `org-mime-export-string`.
In case it is related, I am using emacs 26.2-1 on Arch Linux.

**Comment by redguardtoo** [comment]
286330f fixed: LaTeX fragment not exported correctly (Chen Bin)

**Comment by yangsheng6810** [comment]
Thank you for the quick fix. I would suggest some documentation/comment about this default setting for `org-mime-export-option`.
