### ISSUE TITLE
Configurable export for plain text section

### ISSUE THREAD

**Issue by nickanderson** [org-mime/org-mime#36]
Currently, when you run org-mime-htmlize the original org-mode formatted text is used in the plain text part of the email. It would be nice if there were an option to export the plain text part of the mail message as ascii. org-mode markup is fine for me, but plain ascii is a bit easier to read for non org-mode users.

**Comment by konezny** [comment]
@nickanderson  This capability was added with Pull Request #40.

See [ASCII export options for text/plain](https://github.com/org-mime/org-mime#ascii-export-options-for-textplain).

**Comment by league** [comment]
The text/plain export option seems to work when using `org-mime-org-buffer-htmlize` but if I understand correctly, it is not triggered by `org-mime-htmlize`? Thanks.

**Comment by jtoloe** [comment]
@league `org-mime-htmlize` does not trigger ascii export for me either.

Also related, export options such as `toc:nil` does not seem to be applied to the ascii export. Not even adding a `:EXPORT_OPTIONS: toc:nil` property to the subtree seem to work.

**Comment by konezny** [comment]
@league you are correct. ASCII export was not implemented for `org-mime-htmlize` in Pull Request  #40. I am looking into that now.
@jtoloe I will also look into incorporating export options.
