### ISSUE TITLE
unwanted numbers in displaymath and equation*

### ISSUE THREAD

**Issue by ouboub** [org-mime/org-mime#38]
Hi,
I am running GNU emacs 27 (changeset  "42ba6200af10c00c72ac13912d6fb42a7af88058")
and org-mime Version: 0.1.6, from melpa (Package-Version: 20190805.57)
seems to be the most recent one.

However please consider the following two equations inserted into a mail buffer and exported via 
org-mime-htmlize 
having org-mime-export-options is a variable defined in ‘org-mime.el’.
Its value is (:with-latex dvipng)
``
\begin{displaymath}
\int dx 
\end{displaymath}

\begin{equation*}
\sum
\end{equation*}
''
that looks like a bug
![preview-numbers1](https://user-images.githubusercontent.com/5957203/67956600-a88e4980-fbf4-11e9-8050-ce50cfca85ce.png)

**Comment by redguardtoo** [comment]
org-mime just embedded html/image produced by org export. So it could be your org or latex setup. See https://github.com/org-mime/org-mime/issues/33#issuecomment-479367124 for my investigation.

**Comment by ouboub** [comment]
ok I sent a bug report to hte org maling list and at least one other user can confirm the behaviour I see.
BTW what is the purpose of 
org-mime-htmlize is an autoloaded interactive compiled Lisp function
in ‘~/ALLES/.emacs.d/elpa/org-mime-20190805.57/org-mime.el’.

It is bound to <C-f31>, <C-next>.

(org-mime-htmlize)

This function has :around advice: ‘ad-Advice-org-mime-htmlize’.

Export a portion of an email to html using ‘org-mode’.
If called with an active region only export that region, otherwise entire body.

**Comment by ouboub** [comment]
and another question, Just opened the png generated by org, they do not contain numbers.
I attach them so I think the culprit is org-mime-htmlize
![latexDCECWR_228917e5a4b56f834981c91bb82d9c5f0e6b19a2](https://user-images.githubusercontent.com/5957203/68030408-b528a580-fcb9-11e9-8e4b-d7d0bfb6dda4.png)
![latexGQMoAM_21438cbe28f7ae574702a9abadda00220f82d273](https://user-images.githubusercontent.com/5957203/68030419-b8bc2c80-fcb9-11e9-91e7-aa647ea3475f.png)

**Comment by ouboub** [comment]
Sorry I just looked at the html code before sending, please note; 
<#multipart type=alternative>
<#part type=text/plain>\begin{equation*}
 \int
\end{equation*}
<#multipart type=related><#part type=text/html>
<div class="equation-container">
<span class="equation">
<img src="cid:_tmp_ltximg_latexB0E8nD_cf6140609b8e4081497c2b43eff0f6b9cc72650f.png" alt="latexB0E8nD_cf6140609b8e4081497c2b43eff0f6b9cc72650f.png" />
</span>
<span class="equation-label">
1
</span>
</div>
<#part type="image/png" filename="/tmp/ltximg/latexB0E8nD_cf6140609b8e4081497c2b43eff0f6b9cc72650f.png" disposition=inline id="<_tmp_ltximg_latexB0E8nD_cf6140609b8e4081497c2b43eff0f6b9cc72650f.png>">
<#/part>
<#/multipart>
<#/multipart>

there is 
<span class="equation-label">
1
</span>

this is caused by org-mime-htmlize

**Comment by ouboub** [comment]
SOLVED
a discussion in the org-mode mailing list helped to localize the problem, the culprit was ox-html
thibault marin send a patch which I applied to the lastest org master, the problem of the unwanted 
equations is done. Maybe it is worth to mention that somewhere in your documentation, because 
that problem occurs when using org-mime in the context I described.

**Comment by redguardtoo** [comment]
Sure. Could you send me the link of the mailing list?

**Comment by ouboub** [comment]
Sure
https://lists.gnu.org/archive/html/emacs-orgmode/2019-11/threads.html

**Comment by redguardtoo** [comment]
dd9dac7 doc on html export (Chen Bin)

**Comment by redguardtoo** [comment]
BTW, there is `org-html-hook`. Inside hook, the current buffer is the exported html to be embedded in mail. You can always hack the html directly.

**Comment by ouboub** [comment]
Hm I am not sure I understand your suggestion. The patch of TIbur does the right thing. Do you say the patch could somehow be applied inside that hook? Or what do you propose?

**Comment by redguardtoo** [comment]
Hook is just a dirty and cheap way to hack the output html if you don't have too much time. The patch is the clean and the right way.
