### ISSUE TITLE
wrong path of figures

### ISSUE THREAD

**Issue by QikeLi** [org-mime/org-mime#4]
Hi, 

Thank you for the awesome package. I use org-mime to send a .org file, in which there are code blocks to generate figures. When org-mime generate HTML scripts as the body of the email, in front of the path of the figures the following string is automated generated:
        "/var/folders/p1/0dcc6dpj24q02m7kxys93s3m0000gp/T/file: "

This causes the error--"figures can not be found". And after I delete the string, the email can be successfully sent. Any hints how to solve this? Thank you!

**Comment by redguardtoo** [comment]
Can you give me more details?

**Comment by redguardtoo** [comment]
Can't reproduce with latest org-mime
