### ISSUE TITLE
Syntax highlighting the org-mode syntax while editing the email

### ISSUE THREAD

**Issue by Ekleog** [org-mime/org-mime#44]
Hello,

I've just discovered org-mime, and a first use of it makes me think it looks great!

That said, the link that referred me to org-mime ([here](https://vxlabs.com/2015/01/28/sending-emails-with-math-and-source-code/)) also mentions another feature that AFAIU org-mime doesn't have: syntax highlighting for org-mode syntax within the message-writing buffer.

Do you feel like it'd be possible to do? As a workaround, `M-x org-mode` then `M-x notmuch-message-mode` does work, but it requires manual intervention, and it feels like it'd be even greater if it could just be auto-syntax-highlighted :)

What do you think about this?

**Comment by redguardtoo** [comment]
Interesting idea. I'm not sure how can I mix the `org-mode` and `message-mode`.
Maybe a different solution, I could add a command to open a new buffer to edit org code.

**Comment by Ekleog** [comment]
That totally makes sense too! I think what the link does is basically, when the cursor is in the headers then it switches `message-mode`, and when the cursor is in the body it switches to `org-mode`.

Now, I guess an issue `org-mime` would have is that eg. `notmuch-message-mode` isn't actually `message-mode`, so it'd need to somehow record which major mode was being used before switching to `org-mode`, and then re-use it when going back to the headers.

And here it reaches beyond than my current understanding of elisp, so… I can't say any more :/

**Comment by redguardtoo** [comment]
484bf3b can edit mail-body in org-mode buffer directly (Chen Bin)

**Comment by Ekleog** [comment]
This looks great, thank you! Should we close, or do you plan on doing more on this topic and keeping this open to track the “more”? (not sure what said more would be, but… :))

**Comment by redguardtoo** [comment]
You could close this one. Raise another ticket if you got new feature request.

**Comment by Ekleog** [comment]
Great, thank you!
