### ISSUE TITLE
Automatically handle image attachments

### ISSUE THREAD

**Issue by nickanderson** [org-mime/org-mime#47]
When I insert images into an org buffer I commonly do so using [org-download](https://github.com/abo-abo/org-download). This inserts the image as an attachment and links to the file using `attachment:filename`, for example:

```
#+CAPTION: https://xkcd.com/936/
#+DOWNLOADED: https://imgs.xkcd.com/comics/password_strength.png @ 2020-08-31 12:29:33
[[attachment:2020-08-31_12-29-33_password_strength.png]]
```

When I org-mime-htmlize I get this html:

```
<div class="figure">
<p><a target="_blank" href="2020-08-31_12-29-33_password_strength.png">2020-08-31_12-29-33_password_strength.png</a>
</p>
</div>
```

I currently work around this by first manually re-writing the link using the full path to the file.

It would be nice and convenient if that happened automatically.

**Comment by redguardtoo** [comment]
See `org-mime-pre-html-hook`. Maybe you can convert `[[attachment:file-path]]` to `[[file:file-path]]` in current buffer?

org-mime does not know how to convert org to html. Org-mode exporting does the conversion.

**Comment by nickanderson** [comment]
Ah, OK, thanks.
