### ISSUE TITLE
org-mime attachment issue

### ISSUE THREAD

**Issue by redguardtoo** [org-mime/org-mime#5]
https://www.reddit.com/r/emacs/comments/6qx5uk/attachmentsimages_with_orgmime_compose/

**Comment by amosbird** [comment]
um, I encountered similar issues. My clients cannot receive the attachment of my email. I've forwarded one of that email to you :)

**Comment by redguardtoo** [comment]
There is no problem to attach files. use `M-x mml-attach-file` which has nothing to do with `org-mime` and should not be encoded by `org-mime`.

If you want to embed image in mail body, check readme.

**Comment by amosbird** [comment]
Ok, i'll try to reproduce it. btw, how can I get rid of this line `#+OPTIONS: latex:t toc:nil H:3` ?

**Comment by redguardtoo** [comment]
just delete it. You could setup in you Gnus setup instead, see README

**Comment by averter** [comment]
Thanks @redguardtoo. I was really looking into how to attach files: the `M-x mml-attach-file` does the trick. There are just two issues.  1) Some code is displayed in the message body as a consequence of attaching a file, and it shows amongst other things where the file is located (example below).
````
<#part type="image/gif" filename="~/Downloads/random.gif" disposition=attachment>
<#/part>
````
2) Minor thing but, is it possible to bind the command to `C-c C-a` (the one I use in mu4e with a plain text message). This way my brain won't have to switch when using org-mime. 
Massive thanks for any help on any of these two questions.
