### ISSUE TITLE
FYI hook to ask whether to send non-mime email

### ISSUE THREAD

**Issue by borwickatuw** [org-mime/org-mime#50]
I'm not sure whether there's a good place to put this code, e.g. in a FAQ? I just wrote this to confirm whether to send an email if org-mime-htmlize hasn't been run. In my case I'm using notmuch so I add this to `notmuch-mua-send-hook`.

```
(defun search-for-multipart ()
    "Searches for multipart code and prompts whether to send email"
    (let ((found-multipart
	   (save-excursion
	     (save-restriction
	       (widen)
	       (goto-char 1)
	       (search-forward "<#multipart type=alternative>" nil t))))
	  )
      (if (not found-multipart)
	  (if (not (y-or-n-p "org-mime-htmlize not called; send anyway?"))
	      (setq quit-flag t)))
      ))
(add-hook 'notmuch-mua-send-hook 'search-for-multipart)
```

**Comment by redguardtoo** [comment]
Good idea. Maybe you can create a new function in `org-mime` and send me the pull request, code need a little bit clean up.
```
(defun org-mime-search-for-multipart ()
  "Searches for multipart code and prompts whether to send email"
  (let ((found-multipart (save-excursion
                           (save-restriction
                             (widen)
                             (goto-char (point-min))
                             (search-forward "<#multipart type=alternative>" nil t)))))
    (when (and (not found-multipart)
               (not (y-or-n-p "org-mime-htmlize not called; send anyway?")))
      (setq quit-flag t))))
```

Could you test this function by adding it into `message-send-hook`?

`notmuch-mua-send-hook` calls `notmuch-mua-message-send-hook` which calls `message-send-hook`.

BTW, what's `quit-flag`?

**Comment by borwickatuw** [comment]
OK will do!
`quit-flag` is apparently how `C-g` works: https://www.gnu.org/software/emacs/manual/html_node/elisp/Quitting.html
I don't know a lot about elisp but setting `quit-flag` seemed like the simplest way to stop the message from sending.

**Comment by redguardtoo** [comment]
sure. `quit-flag` looks ok.

**Comment by borwickatuw** [comment]
OK I created pull request #51 ! Thanks!
