### ISSUE TITLE
org-mime-org-buffer-htmlize does not respect File Properties

### ISSUE THREAD

**Issue by nickanderson** [org-mime/org-mime#58]
I have tried two different styles of file properties:

```
#+PROPERTY: MAIL_SUBJECT My mail subject
#+PROPERTY: MAIL_TO Someone <someone@somewhere.tld>
#+PROPERTY: MAIL_FROM Me <me@mine.tld>
```

And

```
:PROPERTIES:
:MAIL_SUBJECT: My mail subject
:MAIL_TO: Someone <someone@somewhere.tld>
:MAIL_FROM: Me <me@mine.tld>
:END:
```

I expected that running `org-mime-org-buffer-htmlize` would fill the email fields as `org-mime-org-subtree` does when the DRAWER style syntax above is placed inside the subtree heading. Instead, the fields are not populated as expected and other defaults are used.

**Comment by redguardtoo** [comment]
24d284f use buffer properties (Chen Bin)
