### ISSUE TITLE
Messages received in Gmail only show plain text

### ISSUE THREAD

**Issue by trev-dev** [org-mime/org-mime#61]
Not sure what's going on, but when I receive test messages sent to a Gmail account, the HTML multipart is totally missing.

It just shows the plain text.

I feel like my config is pretty simple, I'm not sure where I may be going wrong here. Has anyone else seen this?

**Comment by redguardtoo** [comment]
I can't reproduce with latest version,
![image](https://user-images.githubusercontent.com/184553/140596722-9d80d2aa-ea87-4063-b9c0-8dfb6bd9da06.png)

Could you give me more details?

**Comment by trev-dev** [comment]
Hello @redguardtoo - it appears to be working fine when sending via Google's SMTP service. The problem happens consistently for me when I use my ProtonMail account via the Proton Bridge.

I suspect, perhaps, either the bridge or the mail service itself may be picky about the multipart formatting. After doing a quick search I was able to find this: https://github.com/ProtonMail/proton-bridge/issues/18 :/

I think you're good here.

**Comment by redguardtoo** [comment]
Check `org-mime-apply-html-hook`, you can remove plain text content and just keep html content. maybe that will work.

**Comment by trev-dev** [comment]
@redguardtoo maybe it will! I still believe the text multipart is important enough to preserve and would prefer to keep it.

**Comment by trev-dev** [comment]
I'm in a tangle with ProtonMail support over making this work.

I fully expect them to come back at me with some nonsense about it being unsupported, even after providing multiple header examples.

If I can figure out how to use `org-mime-apply-html-hook` to accomplish an HTML-only version that is perhaps still revertable with `org-mime-revert-to-plain-text-mail` would you be open to a pull request @redguardtoo?

**Comment by redguardtoo** [comment]
@trev-dev 

Try this,
```lisp
(defun org-mime-insert-html-content-hack (&rest arg)
  (let* ((txt-sep "<#part type=text/plain")
         (html-sep "<#part type=text/html>")
         txt-beg
         txt-end)
    (save-excursion
      (goto-char (point-min))
      (setq txt-beg (search-forward txt-sep (point-max) t))
      (setq txt-end (search-forward html-sep (point-max) t))
      (when (and txt-beg txt-end)
        (delete-region (- txt-beg (length txt-sep)) (- txt-end (length html-sep)))))))
(advice-add 'org-mime-insert-html-content :after #'org-mime-insert-html-content-hack)
```

**Comment by trev-dev** [comment]
That worked, but unfortunately ProtonMail's servers still mangled the headers/separators somehow and all that came through this time was strangely formatted plain text.

Really not sure what their issue is. Maybe it's the separator, or the header, or both.

**Comment by redguardtoo** [comment]
Sure. You could ask ProtonMail tech support to figure out what html format they expect first. Then you can change the html output in advice or in hook.

**Comment by trev-dev** [comment]
I've sent them multiple examples into, out of and outside of their mail service entirely. They're getting back to me when they can. Thanks again for looking after me
