### ISSUE TITLE
Image paths are not found on Windows

### ISSUE THREAD

**Issue by fleimgruber** [org-mime/org-mime#62]
On Windows, at https://github.com/org-mime/org-mime/blob/master/org-mime.el#L366 valid paths such as "c:/Users/user/path/to/file.png" get prepended with a "/" resulting in "/c:/Users/user/path/to/file.png" which is not a valid Windows path anymore and `(file-exists-p)` errors afterwards at https://github.com/org-mime/org-mime/blob/master/org-mime.el#L390.

**Comment by redguardtoo** [comment]
3b119a2 handle file url on Windows elegantly (Chen Bin)

**Comment by fleimgruber** [comment]
Thanks for the prompt fix! Looking forward to trying it when this lands on MELPA.

**Comment by fleimgruber** [comment]
Turned out I had an outdated org installation around, works now, thanks!
