### ISSUE TITLE
when using a tag like <#secure method=smime mode=sign> org-mime-htmlize moves this tag to the end of the message.

### ISSUE THREAD

**Issue by ouboub** [org-mime/org-mime#63]
Hi
Say I have a message that looks like
```
To: Uwe Brauer <oub@mat.ucm.es> 
Subject: test smime
From: Uwe Brauer <oub@mat.ucm.es>
Gcc: nnml+archive:sent-mail
--text follows this line--
<#secure method=smime mode=sign>
This is a test
```
the org-mime-htmlize converts this to 
```
To: Uwe Brauer <oub@mat.ucm.es> 
Subject: test smime
From: Uwe Brauer <oub@mat.ucm.es>
Gcc: nnml+archive:sent-mail
--text follows this line--
<#multipart type=alternative>
<#part type=text/plain>

This is a test
<#part type=text/html>
<p>
This is a test
</p>
<#/multipart>

<#secure method=smime mode=sign>
```
which is wrong the tag should stay at its place. I swore this did not happen in older version of org-mime

Uwe Brauer

**Comment by redguardtoo** [comment]
Could you give me a bit more information about `<#secure` tag? Why it should stay on the top of the email body?

**Comment by ouboub** [comment]
Sure. It is generated by the function 
```
(mml-secure-message-encrypt-smime nil) 
(from mml-sec.el)
functions that do the encryption are fond in epg.el and epa.el
```
When it stays at the top of the body and the send function is run, then the message is encrypted and signed using smime (not pgp or gpg), in fact it uses the external program (on my Ubuntu machine) gpgsm.

So if the tag is at the end no encryption and signing is done.

**Comment by redguardtoo** [comment]
Could you test this version of `org-mime.el`? Is it fixed?
https://github.com/org-mime/org-mime/blob/secure-tags/org-mime.el

**Comment by ouboub** [comment]
I pulled (by the way the makefile, when running make does not compile at least not for me).

The new commit works, however on small comment:
if I start with 
```
To: Uwe Brauer <oub@mat.ucm.es> 
Subject: test
From: Uwe Brauer <oub@mat.ucm.es>
Gcc: nnml+archive:sent-mail
--text follows this line--
<#secure method=smime mode=sign>

This 

    1. First
```
then org-mime-htmlize inserts a new empty line first.
and I obtain:
```
To: Uwe Brauer <oub@mat.ucm.es> 
Subject: test
From: Uwe Brauer <oub@mat.ucm.es>
Gcc: nnml+archive:sent-mail
--text follows this line--

<#secure method=smime mode=sign>
<#multipart type=alternative>
<#part type=text/plain>


This 

    1. First<#part type=text/html>
<p>
This 
</p>

<ol class="org-ol">
<li>First</li>
</ol>
<#/multipart>
```

that is ok, I am just wondering what is the purpose of that line. 

otherwise: THANKS for the quick fix

**Comment by ouboub** [comment]
SORRY, it is NOT fixed, I did not realise: **the empty line prevents the encryption**

**Comment by ouboub** [comment]
Here is a _patch_
[secure-tag.txt](https://github.com/org-mime/org-mime/files/7785418/secure-tag.txt)

**Comment by redguardtoo** [comment]
59bf130 secure tag should be at the beginning of email body (Chen Bin)
