### ISSUE TITLE
Adding this package to NonGNU ELPA

### ISSUE THREAD

**Issue by skangas** [org-mime/org-mime#65]
Hi!

I am investigating if we could add this package to [NonGNU ELPA](http://elpa.nongnu.org/) (see link), a new Emacs Lisp package archive that will be enabled by default in Emacs 28. This means that users of that version or later will be able to install this package without any configuration: they can just run `M-x list-packages` and install it out of the box. We hope that this will improve Emacs and help bring new users to this package and others.

The main difference between NonGNU ELPA and MELPA is that only stable versions of packages are released. A new release will be made automatically when you bump the ";; Version: NNN" commentary header in this repository. NonGNU ELPA does not look at any "git tag". In the future, you can bump the package version in that header (thereby releasing a new version) when you think it makes sense and at your convenience.

The rules for accepting a package into NonGNU ELPA are here, for your reference:
https://git.savannah.gnu.org/cgit/emacs/nongnu.git/tree/README.org#n133

As far as I can tell, this package already follows the rules so there should be nothing more to do with regards to that. However, it would be good if you could review them and let us know if you think there will be any problems with following any of them going forward. They should be straightforward and easy to follow, but note in particular that NonGNU ELPA does not distribute any package that recommends proprietary software.

For now, it seems like there are no issues with adding this package, but please let me know if you have any comments or questions about NonGNU ELPA. Otherwise, I will go ahead and add this package to the archive.

Thanks!

**Comment by redguardtoo** [comment]
It would be great that  `org-mime` could be added into NonGNU ELPA. Please do so.

Besides, here are my packages I'd like to add to NonGNU ELPA, they all use GPL3 license,

    evil-matchit and evil-nerd-commenter. Their dependency is only evil which is already in the NonGNU ELPA

    find-file-in-project,no dependency

    company-ctags whose dependency is company-mode which is already in GNU ELPA

    counsel-etags whose dependency is counsel which is already in GNU ELPA

    wucuo, no dependency

    find-by-pinyin-dired the only dependency is pinyinlib which could be easily included into NonGNU ELPA because it has no dependency

    elpa-mirror, no dependency

    cliphist, no dependency

    vc-msg, no dependency

    eacl, no dependency

    dianyou, no dependency

    mybigword, no dependency

    js2hl, only dependency is js2-mode which is in GNU ELPA

    imenu-extra, no dependecy

    shellcop, no dependency

    org-mime, no dependency

**Comment by skangas** [comment]
Thanks! Now added: http://elpa.nongnu.org/nongnu/org-mime.html

I have noted down the names of the packages you mention; if you want us to add them faster, feel free to send patches! ;-)
