### ISSUE TITLE
add "alert" format to org-mime

### ISSUE THREAD

**Issue by amosbird** [org-mime/org-mime#7]
Hi, when sending email with important text (such as date), I'd like to mark them with red color. I wonder if we can have this feature in org-mime. There is a similar discussion in `ox-beamer` https://lists.gnu.org/archive/html/emacs-orgmode/2013-05/msg00013.html

**Comment by redguardtoo** [comment]
when you say important text, you mean `_text_` or `*text*`?

**Comment by amosbird** [comment]
no, I mean text with red color.

**Comment by redguardtoo** [comment]
then how you define the text with red color in org-mode?

**Comment by redguardtoo** [comment]
you can check `org-html-text-markup-alist` and  `org-emphasis-alist` if you want to define your own style and emphasis symbol

**Comment by amosbird** [comment]
Thanks. Can I add new entry to  `Org Html Text Markup Alist` ?

**Comment by redguardtoo** [comment]
sure

**Comment by amosbird** [comment]
hmm, I've modified those alist like this,
```
org-emphasis-alist:
[INS] [DEL] List:
            Marker character: @
            Choice: [Value Menu] Font-lock-face: (sample) alert-urgent-face
            [ ] verbatim
```

and 

```
org-html-text-markup-alist:
[INS] [DEL] Markup type: alert
            Format string: <font color="FF0000">%s</font>
```

neither of them works. I don't get the html tag after html export, nor do I have org mode render `@alert@` as red.

**Comment by redguardtoo** [comment]
I think you can only tweak the existing symbol. see https://lists.gnu.org/archive/html/emacs-orgmode/2012-08/msg00700.html (the developers made the decision) and https://emacs.stackexchange.com/questions/5889/how-to-highlight-text-permanently-in-org-mode. Quick and dirty solution.

But I can tweak org-mime and you can use whatever symbol you want. Let me think about what's the best UI.

**Comment by amosbird** [comment]
fwiw, http://orgmode.org/worg/exporters/beamer/tutorial.html  uses `@` for alert.

**Comment by redguardtoo** [comment]
actually, org-mime already provides hook to convert html:

```lisp
(add-hook 'org-mime-html-hook
          (lambda ()
            (while (re-search-forward "@\\([^@]*\\)@" nil t)
              (replace-match "<span style=\"color:red\">\\1</span>"))))
```

**Comment by amosbird** [comment]
ok, thanks.
