### ISSUE TITLE
Different syntax for colored text

### ISSUE THREAD

**Issue by ouboub** [org-mime/org-mime#70]
Hi 
currently the documentation states:
```
(add-hook 'org-mime-html-hook
          (lambda ()
            (while (re-search-forward "@\\([^@]*\\)@" nil t)
              (replace-match "<span style=\"color:red\">\\1</span>"))))
```
the problem with this approach are false positives. I sometimes insert email address like
user@gmail.com
and that leads to undesired effects. 

I recommend to use # instead of @
regards

Uwe Brauer

**Comment by redguardtoo** [comment]
fc3ac72 doc (Chen Bin)
