### ISSUE TITLE
\\ not removed in org-mime-htmlize text/plain output

### ISSUE THREAD

**Issue by jonkri** [org-mime/org-mime#71]
`org-mime-htmlize` converts...

```
Text\\
Text
```

... to:

```
<#multipart type=alternative>
<#part type=text/plain>
Text\\
Text<#part type=text/html>
<p>
Text<br />
Text</p>
<#/multipart>
```

I was expecting `\\` on line 3 to be removed:

```
<#multipart type=alternative>
<#part type=text/plain>
Text
Text<#part type=text/html>
<p>
Text<br />
Text</p>
<#/multipart>
```

Is this a bug?

**Comment by redguardtoo** [comment]
Why `//` should be removed?

**Comment by jonkri** [comment]
> Why `//` should be removed?

Hi, @redguardtoo!

I believe `\\` (backslashes, not `//`) should be removed because it represents a line break.

`\\` is replaced with `<br />` in the HTML output. I'm thinking the equivalent in plain text is a line break.

**Comment by redguardtoo** [comment]
In `org-mime-html-hook` you can hack the exported html.

**Comment by jonkri** [comment]
> In `org-mime-html-hook` you can hack the exported html.

Good to know, thanks!

Is there a way to hack the exported text as well?

(The HTML looks fine in my example above, it's the plain text that's the problem.)

**Comment by jonkri** [comment]
Just to clarify:

I'm assuming that this in Org mode...

```
Text\\
Text
```

... should be “exported” to this in plain text:

```
Text
Text
```

(Since we don't need a special symbol for line breaks (like `\\`) in plain text.)

**Comment by redguardtoo** [comment]
f321d06 hook to post-process plain text email (Chen Bin)

**Comment by jonkri** [comment]
Thanks a lot! :muscle: 

For anyone else looking for a way to replace `\\` (at the end of lines, which I'm guessing is all that's needed here), perhaps this can be of some help:

```el
(add-hook 'org-mime-plain-text-hook
          (lambda ()
            (while (re-search-forward "\\\\\\\\$" nil t) (replace-match ""))))
```

Closing.
