### ISSUE TITLE
"org-mime-extract-non-org: "<#part " should have end tag." when using a signature

### ISSUE THREAD

**Issue by jonkri** [org-mime/org-mime#72]
org-mime-htmlize converts...

```
Text

-- 
Signature
```

... to...

```
<#multipart type=alternative>
<#part type=text/plain>
Text

<#part type=text/html>
<p>
Text
</p>
<#/multipart>
-- 
Signature
```

... and when I try to send that message (using C-c C-c) I'm getting this error:

> org-mime-extract-non-org: "<#part " should have end tag.

Is this a bug?

**Comment by redguardtoo** [comment]
7f477f2 only match attachment tag (Chen Bin)

**Comment by jonkri** [comment]
Thanks! :slightly_smiling_face:
