### ISSUE TITLE
Force push blocking further NonGNU ELPA releases

### ISSUE THREAD

**Issue by monnier** [org-mime/org-mime#74]
It seems that the main branch has seen a force push, which prevents the downstream `nongnu.git` repository (from which NonGNU ELPA packages are built) from updating because it can only do that reliably via fast-forwards.

```
% make fetch/org-mime
emacs --batch -l admin/elpa-admin.el -f elpaa-batch-fetch-and-show "org-mime"
Fetching updates for org-mime...
Upstream of org-mime has DIVERGED!

  Local changes:
Depuis https://github.com/org-mime/org-mime
 * [nouvelle référence]               -> upstream/org-mime/main
fc3ac72c3a  chenbin.sh@gma..  doc

  Upstream changes:
3f1f3a3842  chenbin.sh@gma..  hook to post-process plain text email
f831a69284  chenbin.sh@gma..  doc on hacking exported html
3facf18272  chenbin.sh@gma..  only match attachment tag
c4268dbca5  chenbin.sh@gma..  doc

%
```

Could you please fix the Git metadata with something like:

    git merge -s ours fc3ac72c3a

so that NonGNU ELPA can keep tracking your code?

**Comment by redguardtoo** [comment]
Could you show me your git repo? I can't find the commit

**Comment by monnier** [comment]
Thank you!

**Comment by monnier** [comment]
Chen Bin [2022-02-05 02:50:39] wrote:
> Could you show me your git repo? I can't find the commit

IIUC you have found it in the mean time, right?
Thanks for fixing this promptly,


        Stefan

**Comment by redguardtoo** [comment]
All good now. No worries
