### ISSUE TITLE
mu4e + org-mime - headers and bold rendered in red 

### ISSUE THREAD

**Issue by practicalwellbeing** [org-mime/org-mime#75]
I'm using mu4e + org-mime to write html emails.

Everything works fine except that <h1>, <h2>, links and bold are rendered in red. The file can be exported to html and it looks fine.

For example 

** Header test

gives 

```
<div id="outline-container-orge8cf032" class="outline-2">
<h2 id="orge8cf032">Header test</h2>

```
my email program gets

```
<h2 style="margin-top :  20px; margin-bottom :  20px; color :  #c01c28; font-size :  18pt; " id="x_-259048000orgb3688d7">Header test </h2>

```
How can I get the headers to display in the 'usual' colours.

**Comment by redguardtoo** [comment]
Looks like it's your email client setup. You could hard code "h2" style in the hooks though.
