### ISSUE TITLE
Plain part does not seem to respect org-mime-export-options (adding author, Table of Contents)

### ISSUE THREAD

**Issue by nickanderson** [org-mime/org-mime#77]
`org-mime-export-options` is set to disable section numbers, author, toc, and title.

    org-mime-export-options is a variable defined in ‘org-mime.el’.
    Its value is
    (:section-numbers nil :with-author nil :with-toc nil title nil)

I composed the email in org, then copied the text to my email buffer which is `mu4e:compose-mode` .

Then I run `org-mime-htmlize`. My email is converted as expected, except the `text/plain` portion contains an Author line and a  Table of Contents (the html part does not). It seems that the plain part export does not respect `org-mime-export-options`.

    From: Nick Anderson <nick@cmdln.org>
    To: 
    Subject: 
    Date: Thu, 05 May 2022 15:07:53 -0500
    --text follows this line--
    <#multipart type=alternative>
    <#part type=text/plain>
    Nick Anderson
    
    
    Table of Contents
    _________________
    
    
    
    
    Hello,
    
    This is an email written in a second level org-heading.
    
    I composed the email in org, then copied the text to my email buffer
    which was <mu4e:compose>
    
    #+begin_example ,* File issue about toc being added in ascii part email
    
    ** Example Email
    
    Hello,
    
    This is an email written in a second level org-heading.
    
      I composed the email in org, then copied the text to my email buffer
    which was <mu4e:compose> #+end_src
    <#part type=text/html>
    <p>
    Hello,
    </p>
    
    <p>
    This is an email written in a second level org-heading.
    </p>
    
    <p>
    I composed the email in org, then copied the text to my email buffer which was <a href="compose">compose</a>
    </p>
    
    <p>
    #+begin_example
      * File issue about toc being added in ascii part email
    </p>
    
    <p>
    ** Example Email 
    </p>
    
    <p>
    Hello,
    </p>
    
    <p>
    This is an email written in a second level org-heading.
    </p>
    
    <p>
      I composed the email in org, then copied the text to my email buffer which was <a href="compose">compose</a>
    #+end_src
    </p>
    <#/multipart>

**Comment by redguardtoo** [comment]
The actual exporting job is done by `org-export-string-as`, see the definition of `org-mime-export-ascii-maybe`. I do pass the options to it. But looks the exporting options only works for html backend.

Anyway, you can use `org-mime-plain-text-hook` to modify the plain text mail.
