### ISSUE TITLE
Regressions in quoting

### ISSUE THREAD

**Issue by madalu** [org-mime/org-mime#79]
Recent changes to org-mime introduced several significant regressions with quoting:

1. org-mime has lost its ability to format both nested quotes and quote snippets for those who use or prefer bottom-posting
2. `&qt;` entities are no longer removed. 
3. Everything beneath the quote separator is deleted in the text/plain mime section of the multipart message (highly undesirable for recipients with plain text mail readers). 

These regressions occured in 2eede712acc5 with the removal of the function org-mime-beautify-quoted. The relevant deletions are here: https://github.com/org-mime/org-mime/commit/2eede712acc51aaf495984ec457431dbb520038c#diff-450a14f141d9c1e1326d26ae4098c6f1bf9077176cd54843c670b358d3b61b72L317-L338

As you can see, the deleted code interated over the reply line by line to distinguish between quoted and non-quoted material. It would wrap each quoted section individually in `<blockquote class="gmail_quote">...</blockquote>`. Now org-mime wraps the entire section beneath the quote separator in a single div and blockquote. This includes both quoted text and my own replies. 

## Illustration of regressions (what currently happens):

Text in message mode before running org-mime-htmlify:

![2022-05-20_16-12](https://user-images.githubusercontent.com/2131453/169611374-049a3807-dd87-4cf1-9d73-b893deba2c25.png)

Text after org-mime-htmlify (note the &qt; entities and the lack of quoted material in the text/plain section):

![2022-05-20_16-13](https://user-images.githubusercontent.com/2131453/169611397-39fcb5a5-8eb8-4708-bf14-df0f7c89c3a8.png)

Browser view of html email:

![2022-05-20_16-13_1](https://user-images.githubusercontent.com/2131453/169611437-48dad91b-eb50-459f-ba36-abe9868a6a64.png)

## What I expect to happen (last good commit = 98504d0):

![2022-05-20_16-15](https://user-images.githubusercontent.com/2131453/169611741-aa90a6ea-9a20-4f6e-8864-40369886692a.png)

Browser view of desired behavior:

![2022-05-20_16-16](https://user-images.githubusercontent.com/2131453/169611749-d099d97c-2381-4cd7-8a3b-af3c9a4c8a59.png)

**Comment by redguardtoo** [comment]
Thanks for the report. I pushed the new feature to quickly. The code has to be rolled back. I need test the gmail friendly feature in new branch and with lots of unit test.

**Comment by redguardtoo** [comment]
rollbacked in 0.3.1
