### ISSUE TITLE
A couple suggestions, not worth a PR (I think?)

### ISSUE THREAD

**Issue by bigodel** [org-mime/org-mime#80]
Just a couple of suggestions of small changes that I didn't feel needed a PR, but I could always submit one if needed.

1. Use the value of `message-signature-separator` by default, if available. So instead of this

   https://github.com/org-mime/org-mime/blob/cf96f585c68ad14751a3f73d937cbfcb890171b9/org-mime.el#L173-L176
   
   we would have

   ```elisp
   (defcustom org-mime-mail-signature-separator
     (or message-signature-separator "^--\s?$")
     "Default mail signature separator."
     :group 'org-mime
     :type 'string)
   ```

2. Use `(org-mime-mail-signature-begin)` as end marker for the message body, and default to `(point-max)`. The following line

   https://github.com/org-mime/org-mime/blob/cf96f585c68ad14751a3f73d937cbfcb890171b9/org-mime.el#L837
   
   would become
   
   ```lisp
   (end (copy-marker (or (org-mime-mail-signature-begin) (point-max))))
   ```

**Comment by redguardtoo** [comment]
Make sense.

5c19b45 special edit buffer should not include signature (Chen Bin)

**Comment by bigodel** [comment]
Thank you very much!
