### ISSUE TITLE
feature suggestion: save to a file

### ISSUE THREAD

**Issue by ouboub** [org-mime/org-mime#81]
Hi 

I sometimes need to convert org files to a simpler form of HTML, as the its standard exporter provides.

org-mime seems to be perfectly suited for this purpose, I have successfully used its generated HTML export, 
and that is why I would like to propose to add an export function in a file not in a message.

could that be easily done?
thanks and regards

Uwe Brauer

**Comment by redguardtoo** [comment]
You can run `M-x org-export-dispatch`

**Comment by ouboub** [comment]
> You can run `M-x org-export-dispatch`

I know, but that would result in using the standard vanilla HTML exporter which results in a rather complex HTML document, while org-mime exports to much smaller and cleaner file, I attach two example, one with the standard HTML one with org-mime using copy and paste (and I want to have a convenient function instead of doing copying and paste)
[example.txt](https://github.com/org-mime/org-mime/files/8986039/example.txt)
[example-org.txt](https://github.com/org-mime/org-mime/files/8986040/example-org.txt)

**Comment by redguardtoo** [comment]
I'm using same api. Looks you only need html body. You can still use `org-html-export-to-html`,
```
Signature
(org-html-export-to-html &optional ASYNC SUBTREEP VISIBLE-ONLY BODY-ONLY EXT-PLIST)
```

Check its 4th parameter `BODY-ONLY`.

Here is my simple wrapper,
```lisp
(require 'ox-html)
(defun my-org-export-to-html ()
  (interactive)
  (org-html-export-to-html nil nil t t))
```

**Comment by ouboub** [comment]
> I'm using same api. Looks you only need html body. You can still use `org-html-export-to-html`,
> 
> ```
> Signature
> (org-html-export-to-html &optional ASYNC SUBTREEP VISIBLE-ONLY BODY-ONLY EXT-PLIST)
> ```
> 
> Check its 4th parameter `BODY-ONLY`.
> 
> Here is my simple wrapper,
> 
> ```lisp
> (require 'ox-html)
> (defun my-org-export-to-html ()
>   (interactive)
>   (org-html-export-to-html nil nil t t))
> ```

ha, correct, thanks a lot I did not realise this!
