### ISSUE TITLE
org-export-barf-if-invalid-backend: Unknown "nil" back-end: Aborting export

### ISSUE THREAD

**Issue by publicimageltd** [org-mime/org-mime#84]
I'm trying `org-mime` with Org Mode version 9.5.2, Emacs version 28.2. I am getting this error:

```
org-export-barf-if-invalid-backend: Unknown "nil" back-end: Aborting export
```

This is my setup:

```
(use-package org-mime
  :after message
  :config
  (setq org-mime-export-options
        `(:with-latex dvipng
                      :title ,nil
                      :section-numbers ,nil
                      :with-author ,nil
                      :with-toc ,nil))
  )
```

Any idea what the problem could be?

**Comment by redguardtoo** [comment]
`M-x toggle-debug-on-error`, reproduce the issue, and give me more details.

`org-mime` only calls org api to export org to html., it doesn't know the lower backend. Have you installed latext packages and try to export an org file without org-mime?

**Comment by publicimageltd** [comment]
Found it. As simple as `(require 'ox-html)'. You should require that somewhere in the code, it makes sense to not depend on it.

Thanks!

**Comment by redguardtoo** [comment]
sure. cc00afc ox-html is required (Chen Bin)
