### ISSUE TITLE
Advice to add figure caption to html email

### ISSUE THREAD

**Issue by ddhendriks** [org-mime/org-mime#89]
In my org buffers I sometimes have images that contain captions through  `#+CAPTION:` (https://orgmode.org/manual/Captions.html). These are, as of yet, not processed in the `org-mime-org-XXX-htmlize` calls. I would like to include these captions in the export.

HTML has the <figure> and <figcaption> elements that can be used for this, but I'm not entirely sure where to start, or whether that is currently possible. 

Any advice?

**Comment by redguardtoo** [comment]
The caption is produced in html. I'm not sure what's the problem. You can change caption's html in the hook, see https://github.com/org-mime/org-mime?tab=readme-ov-file#css-style-customization

**Comment by ddhendriks** [comment]
> I'm not sure what's the problem. 

https://orgmode.org/manual/Captions.html states, 
```
Depending on the export back-end, [captions] may or may not be handled. 
```
My question is whether and how the org-mime export to HTML has access to the information stored in the `+CAPTION: <>` in org-mode, and handles the export to HTML of the text.

> The caption is produced in html.

sure, but it should still be sourced with text to fill the caption.

Am I overlooking something? Might well be the case.

**Comment by redguardtoo** [comment]
org-mime calls org html export backend to convert org to html.  Until the html is produced, it's blackbox for org-mime. It can't understand the org node before conversion.  As I tested in my setup, the caption is converted. 

![image](https://github.com/org-mime/org-mime/assets/184553/5ac4313d-68d2-4b9c-ae0c-b1faf00abf7b)

**Comment by ddhendriks** [comment]
Hi,

The mistake indeed is on my side.

Using an org file that contains an image with a caption like this

```
#+DOWNLOADED: file:<filename> @ 2024-04-02 13:39:39
#+CAPTION: example caption.
[[file:.example-imgs/<filename>]]
```

the html-version of the email constructed with org-mime does indeed contain the caption. I think I structured the caption wrongly before.

![Selection_1950](https://github.com/org-mime/org-mime/assets/74686531/43566533-c09e-4a49-b97b-7b91276f336c)
