### ISSUE TITLE
Define (defgroup) org-mime group

### ISSUE THREAD

**Issue by krisbalintona** [org-mime/org-mime#93]
Currently, org-mime actually doesn't define (defgroup) an org-mime customize group, despite all defcustoms being a part of such a group. I think this causes `M-x customize-group RET org-mime` to not list all customizable options. On my end, only `org-mime-beautify-quoted-mail-p` is shown. Additionally, the customize buffer reports: "org-mime group:  Group definition missing."

**Comment by redguardtoo** [comment]
90aa908 add missing group (Chen Bin)

**Comment by krisbalintona** [comment]
Looks good, thank you!
